/obj/item/rod_of_asclepius/attack_hand(mob/user)
	if(activated)
		visible_message(message=span_notice("[user] pets [src]."),self_message=span_notice("You pet the snake on [src]."),blind_message=span_notice("You hear petting and hissing."))
		playsound(loc, 'sound/weapons/thudswoosh.ogg', 50, 1, -1)
	..()
